# Generated by Django 5.2.5 on 2025-09-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruba', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
