# Generated by Django 5.2.5 on 2025-09-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruba', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
    ]
