# Generated by Django 5.2.5 on 2025-09-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruba', '0007_remove_profile_profile_picture_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
