# Generated by Django 5.2.5 on 2025-09-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruba', '0008_profile_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
